name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ShellCheck scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts'

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            README.md
            documentation.md
